
import './App.css';
import Auth from './Components/Auth';
import { BrowserRouter, Routes, Route } from "react-router-dom";
import HelloWorld from './Components/HelloWorld';
import SearchBreed from './Components/SearchBreed';
import Navbar from './Components/Navbar';

function App() {
  return (
    
    <BrowserRouter>
    <Navbar></Navbar>
      <Routes>
          <Route index element={<HelloWorld />} />
          <Route path="auth/login" element={<Auth />} />
          <Route path="search" element={<SearchBreed />} />
      </Routes>
    </BrowserRouter>
  );
}

export default App;


/*

1. Login and get the authentication, use cookis to stay authenticated
2. Then Land to the search page. Here they Should be able to browse the dogs.
      Second landing Page req:
        -> Filter By Breed
        -> Paginated
        -> Sorted alphabetically -> Default
        -> Can sort in descending as well
        -> Except id all fields for dog should be shown
3. Should be able to select the dogs from their results.
   Generate a match based on however you see fit.
 { A single match will be generated by sending all favorited dog IDs to the 
  /dogs/match endpoint. You should display this match however you see fit.}  Not Sure WHat this is?
*/